version: '3.8'
services:
  openthreatiq:
    build: .
    container_name: openthreatiq
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
